openapi: 3.0.0
info:
  version: 1.0.0
  title: atmster
servers:
  - url: 'https://petstore.swagger.io/v1'
paths:
  /commission:
    get:
      summary: 'Returns cash withdrawal commission'
      operationId: getCommission
      tags:
        - commission
      parameters:
        - name: issuerBankId
          in: query
          description: ID of issuer bank
          required: true
          schema:
            type: integer
            format: int64
        - name: atmBankId
          in: query
          description: ID of the bank ATM belongs to
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Commission for cash withdrawal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commission'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /atm:
    get:
      summary: 'Returns list of ATMs'
      operationId: getATMs
      tags:
        - atm
      parameters:
        - name: currency
          in: query
          description: currency e.g. USD
          required: false
          schema:
            type: string
        - name: boundingbox
          in: query
          description:
          required: false
          schema:
            $ref: '#/components/schemas/BoundingBox'
      responses:
        '200':
          description: List of ATMs that match passed criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfATMs'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
/bank:
    get:
      summary: 'Returns details about a bank by id or BIC'
      operationId: getBank
      tags:
        - banks
      parameters:
        - name: id
          in: query
          description: internal numerical id of a bank
          required: false
          schema:
            type: integer
            format: int64
        - name: bic
          in: query
          description: BIC
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Details about bank with specified id or BIC
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Currency:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    Amount:
      type: object
      required:
        - amount
        - currency
      properties:
        amount:
          type: number
          format: float
        currency:
          type: string
    Bank:
      type: object
      required:
        - id
        - bic
        - name
        - url
      properties:
        id:
          type: integer
          format: int64
        bic:
          type: string
        name:
          type: string
        name:
          type: url
    Location:
      type: object
      required:
        - lat
        - lon
      properties:
        lat:
          type: number
          format: float
        lon:
          type: number
          format: float
    BoundingBox:         
      type: object
      required:
        - leftTop
        - rightBottom
      properties:
        leftTop:
          $ref: '#/components/schemas/Location'
        rightBottom:
          $ref: '#/components/schemas/Location'
    ATM:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        bankId:
          type: integer
          format: int64
        currencies:
          type: array
          items:
              type: string
        location:
          $ref: '#/components/schemas/Location'
        active:
          type: boolean
        hoursOfWork:
          type: string
          description: ToDo
    ArrayOfATMs:
      type: array
      items:
        $ref: '#/components/schemas/ATM'
    Commission: 
      type: object
      required:
        - totalPercent
      properties:
        totalPercent:
          type: number
          format: float
        issuerPercent:
          type: number
          format: float
        issuerCommissionFixedAmount:
          type: number
          format: float
        acquirerPercent:
          type: number
          format: float
        acquirerCommissionFixedAmount:
          type: number
          format: float
        issuerMinCommissionAmount:
          type: number
          format: float
        acquirerMinCommissionAmount:
          type: number
          format: float
        maxWithdrawalAmount:
          type: number
          format: float
        currency:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []