openapi: 3.0.1
info:
  version: 1.0.0
  title: atmster
servers:
  - url: 'https://da7f50c3-7a27-497c-80bb-4a9652cdc548.mock.pstmn.io'
paths:
  /commission:
    get:
      summary: 'Returns cash withdrawal commission'
      operationId: getCommission
      tags:
        - commission
      parameters:
        - name: issuerBankId
          in: query
          description: ID of issuer bank. If not specified, then issuer comissions are not returned.
          required: false
          schema:
            type: integer
            format: int64
        - name: atmBankId
          in: query
          description: ID of the bank ATM belongs to
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Commission for cash withdrawal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commission'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
   post:
      summary: 'Add details about bank's cash withdrawal commission'
      operationId: addCommission
      tags:
        - commission
      parameters:
        - name: bankId
          in: query
          description: ID of bank to add commission for.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: Added commission for cash withdrawal.
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
   put:
      summary: 'Update details about bank's cash withdrawal commission'
      operationId: updateCommission
      tags:
        - commission
      parameters:
        - name: bankId
          in: query
          description: ID of bank to update commission for.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Updated commission for cash withdrawal.
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /atm:
    get:
      summary: 'Returns list of ATMs'
      operationId: getATMs
      tags:
        - atm
      parameters:
        - name: currency
          in: query
          description: currency e.g. USD
          required: false
          schema:
            type: string
        - name: boundingbox
          in: query
          description: recatangle on map used to request atms that reside withing its bounds
          required: true
          schema:
            $ref: '#/components/schemas/BoundingBox'
      responses:
        '200':
          description: List of ATMs that match passed criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfATMs'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: 'Add new ATM'
      operationId: addATM
      tags:
        - atm
      requestBody:
        required: true
        description: ATM to add. Id field should be empty, it will be generated and returned in response.
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/ATM'
      responses:
        '201':
          description: Added ATM with id field populated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ATM'
    put:
      summary: 'Update ATM details'
      operationId: updateATM
      tags:
        - atm
      requestBody:
        required: true
        description: ATM to update.
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/ATM'
      responses:
        '200':
          description: Updated ATM.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ATM'
  /bank:
    get:
      summary: 'Returns details about a bank by id or BIC'
      operationId: getBank
      tags:
        - banks
      parameters:
        - name: id
          in: query
          description: internal numerical id of a bank
          required: false
          schema:
            type: integer
            format: int64
        - name: bic
          in: query
          description: BIC
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Details about bank with specified id or BIC.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: 'Add new bank'
      operationId: addBank
      tags:
        - banks
      requestBody:
        required: true
        description: Bank to add. Id field should be empty, it will be generated and returned as part of response.
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
      responses:
        '201':
          description: Added Bank with id field populated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
    put:
      summary: 'Update bank details'
      operationId: updateBank
      tags:
        - banks
      requestBody:
        required: true
        description: Bank to update.
        content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
      responses:
        '200':
          description: Updated Bank.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
components:
  schemas:
    Currency:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    Amount:
      type: object
      required:
        - amount
        - currency
      properties:
        amount:
          type: number
          format: float
        currency:
          type: string
    Bank:
      type: object
      required:
        - bic
        - name
      properties:
        id:
          type: integer
          format: int64
        bic:
          type: string
        name:
          type: string
        url:
          type: string
        comission:
          $ref: '#/components/schemas/Comission'
    Location:
      type: object
      required:
        - lat
        - lon
      properties:
        lat:
          type: number
          format: float
        lon:
          type: number
          format: float
    BoundingBox:         
      type: object
      required:
        - leftTop
        - rightBottom
      properties:
        leftTop:
          $ref: '#/components/schemas/Location'
        rightBottom:
          $ref: '#/components/schemas/Location'
    ATM:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        bankId:
          type: integer
          format: int64
        currencies:
          type: array
          items:
              type: string
        location:
          $ref: '#/components/schemas/Location'
        active:
          type: boolean
        hoursOfWork:
          $ref: '#/components/schemas/HoursOfWork'
    HoursOfWork:
      type: object
      required:
        - bod
        - eod
      properties:
        bod:
          type: string
          description: beginning of working day
        eod:
          type: string
          description: end of working day
    ArrayOfATMs:
      type: array
      items:
        $ref: '#/components/schemas/ATM'
    Commission: 
      type: object
      properties:
        totalPercent:
          type: number
          format: float
        issuerPercent:
          type: number
          format: float
        issuerCommissionFixedAmount:
          type: number
          format: float
        acquirerPercent:
          type: number
          format: float
        acquirerCommissionFixedAmount:
          type: number
          format: float
        issuerMinCommissionAmount:
          type: number
          format: float
        acquirerMinCommissionAmount:
          type: number
          format: float
        maxWithdrawalAmount:
          type: number
          format: float
        currency:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []